### PR TITLE
netstandard2.0 version

### PR DESCRIPTION
**Pull request by thinkbeforecoding**
This is a conversion to netstandard2.0
The net40 version has been upgraded to net45 to follow FSharp.Core dependencies

The build script has been converted to Fake5
The documentation generation now use FSharp.Literate with a Fable.React template.

### CODE REVIEW

**Comment by thinkbeforecoding** [comment]
Trying to fix the build with travis 😬

**Comment by dsyme** [comment]
@thinkbeforecoding I've added you as co-admin on this repo so you can accept this when complete

**Comment by thinkbeforecoding** [comment]
@dsyme I have hard time making it build on linux… 
the fsc version doesn't seem right… 😬

**Comment by thinkbeforecoding** [comment]
@dsyme I don't know who's responsible for pushing the nuget now

**Comment by sergey-tihon** [comment]
@thinkbeforecoding I can give you access if you give you NuGet account name

**Comment by thinkbeforecoding** [comment]
My NuGet account is thinkbeforecoding 
Do you publish the nuget from your local machine (using the build script of course)

**Comment by thinkbeforecoding** [comment]
@sergey-tihon  I bumped the version to 2.0 since its now >= net461 or netstandard2.0

**Comment by sergey-tihon** [comment]
@thinkbeforecoding Thank you for publishing NuGet package!

**Comment by sergey-tihon** [comment]
Are you sure that NuGet package dependencies are correct? 
`FSharp.Core (>= 0.0.0)`

**Comment by thinkbeforecoding** [comment]
Mh.. doesnt seem great… what would be the best version to depend on ?

**Comment by sergey-tihon** [comment]
4.3.4?

## FSharp.Data.SqlClient 
NuGet_Gallery___FSharp_Data_SqlClient_2_0_5

## FSharp.Data
NuGet_Gallery___FSharp_Data_3_1_1

**Comment by thinkbeforecoding** [comment]
Done in #25

**Pull request merged**
