### PR TITLE
Fixing #20

### PR DESCRIPTION
**Pull request by realvictorprm**
This adds support for accessing the values of the match groups directly through using e.g. the type provided by TryTypedMatch method.

### CODE REVIEW

**Comment by realvictorprm** [comment]
darn forgot the tests :sweat_Smile:

**Comment by realvictorprm** [comment]
Okay question fellows. Which tests are fine for the regex provider? Is the current provider fine with giving values as `value_{value_name}` ?

**Comment by realvictorprm** [comment]
Reminder to myself. I need to fix the tests and get this ready to merge.

**Comment by thinkbeforecoding** [comment]
@realvictorprm what is the status of this PR ?
Maybe we can create a new one on new version ?

**Comment by thinkbeforecoding** [comment]
Genuine question:
@realvictorprm what is the benefit of a new property value_groupname over groupname.Value ?

**Comment by thinkbeforecoding** [comment]
done in #30

**Comment by realvictorprm** [comment]
Sorry I have no idea anymore what I've done here. It's been a while lol

**Pull request closed without merging**
